Catch all exceptions in PM's call to get_pool()
Unhandled exceptions in central, during PM start, can cause PM to fail. For
example, if pool managers called to central.get_pool() fails with, say an
OperationalError: (2013, 'Lost connection to MySQL server during query'),
then PM will crash out.

Change-Id: If076c451e8f9802a24f75d103dece8d1bf06af87
Closes-Bug: 1583982